name: Comunicador de la legion 

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Qué villano envia el mensaje?"
        required: true
        type: choice
        options: 
          - Lex Luthor
          - Magneto
          - Joker
          - Mystique
          - Brainiac

      mensaje:
        description: "Mensaje para el consejo"
        required: true
        default: "La misión fue un éxito"
      
      cow-character:
        description: "Tipo de Cow"
        required: true
        type: choice
        options: 
          - armadillo
          - aperture
          - atom
          - banana

      prioridad:
        description: "Nivel de Prioridad"
        required: true
        type: choice
        options: 
          - 🟢Normal
          - 🟡Alta
          - 🔴Crítica
jobs:
  transmitir-mensaje:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Instalar el transmisor de la legión
        run: sudo apt-get install -y cowsay

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Imprimir Inputs
        run: |
          echo "================================="
          echo "    Tranmisión Interceptada"
          echo "================================="
          echo ""
          echo "De: ${{inputs.villano}}"
          echo ""
          echo "Fecha: $(data -u +"%d/%m/%Y - %H:%M UTC")"
          echo "---- Mensaje ----"
          cowsay -f "${{inputs.cow-character}}"
          echo ""
          echo "---- ${{inputs.villano}}"
          echo "..."
          